"""remind_at field edited

Revision ID: 3d3669015f9a
Revises: b8e69d31c251
Create Date: 2024-04-17 14:55:23.555317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3669015f9a'
down_revision = 'b8e69d31c251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_reminder', schema=None) as batch_op:
        batch_op.alter_column('remind_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_reminder', schema=None) as batch_op:
        batch_op.alter_column('remind_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
