"""Add 'sent' column to ParsedReminder

Revision ID: 70001eb86015
Revises: 3d3669015f9a
Create Date: 2024-05-03 00:16:29.744666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70001eb86015'
down_revision = '3d3669015f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_reminder', schema=None) as batch_op:
        batch_op.drop_column('sent')

    # ### end Alembic commands ###
